name: Actions workflow

on: [push]

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Actions
        id: greet
        uses: Yashvanth2498/hello-world-javascript-action@22921edcd03f458f756d959e06e47685e117db1f #Instead of master we can use versions or commit id
        # Using master or branch is not preferred. Commit id is preferred.
        with: 
          who-to-greet: John
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"   